#!/usr/bin/env bash
conda activate occlum_ray

pushd /root/codes/occlum_ray/ray/python
python setup.py bdist_wheel
mv dist/ray-1.13.0-cp38-cp38-linux_x86_64.whl /root/codes/occlum_ray/occlum-ray-docker 
popd

pushd /root/codes/occlum_ray/occlum-ray-docker
docker build -t occlum_ray .
echo "done."

# To run the container with SGX
# docker run -it --device /dev/sgx/enclave --device /dev/sgx/provision --shm-size=512m occlum_ray:latest

# Enter container
# docker exec -it {container_id} bash

# Inside the container, run a program (python) inside OcclumOS:
occlum run /bin/python3.8 -c '
import ray


ray.init(
    object_store_memory=100 * 1024 * 1024,
    _temp_dir="/host/tmp/ray",
)

@ray.remote
def foo(x):
    return ray.put(f"Result data is: {x + 1}")

value = ray.get(ray.get(foo.remote(1)))
print(value)
assert value == "Result data is: 2"
' > tmp.log 2>&1
